LDEV-748 LPGS install - do not install this module as a zip file
When importing the module installed as a zip file, you get the error:
 zlib.error: Error -2 while decompressing data: inconsistent stream state
So it is installed as a directory instead.